services:
  # masstransitlearning.api:
  #   # image: ${DOCKER_REGISTRY-}masstransitlearningapi
  #   build:
  #     context: .
  #     dockerfile: MassTransitLearning.API/Dockerfile
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_HTTP_PORTS=8080
  #     - ASPNETCORE_HTTPS_PORTS=8081
  #     - Mongo__ConnectionString=mongodb://mongo
  #     - Mongo__DatabaseName=testing
  #     - RabbitMQ__Host=rabbitmq
  #     - RabbitMQ__User=user
  #     - RabbitMQ__Pass=bitnami
  #     - ASPNETCORE_Kestrel__Certificates__Default__Password=localpassword
  #     - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
  #   ports:
  #     - "8080:8080"
  #     - "8081:8081"
  #   volumes:
  #     - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
  #     - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  #     - ./aspnetapp.pfx:/https/aspnetapp.pfx:ro
  #   depends_on:
  #     - rabbitmq
  #     - mongo

  rabbitmq:
    container_name: rabbitmq
    image: bitnami/rabbitmq:4.0
    environment:
      - RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS=true
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 30s
    ports:
      - "5671:5671"
      - "5672:5672"
      - "4369:4369"
      - "15691:15691"
      - "15692:15692"
      - "15672:15672"

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password